### ISSUE TITLE
ex:(Rebuild Failure) ; Visual Build Inconsistency

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai-unity-project#6]
I rebuilt this on Windows 11 and the lighting is noticeably darker and signposter boards do not work (showing only grey surfaces). I changed nothing about the build itself. Very strange...

**Comment by alhasacademy96** [comment]
<img width="1250" alt="2020 3 9f1 version + code changes vs no code changes" src="https://user-images.githubusercontent.com/65875290/224706699-2b4b6c5c-8ac6-47be-85e9-812f28564652.png">

Figure 1.0 ^

Both builds are running 2020.3.9f1. Left build has camera manual episode change disabled; right build has camera and manual episode change enabled. Both builds have shadows darker and no signboards are showing in another separate test.

**Comment by alhasacademy96** [comment]
<img width="1250" alt="latest unity editor + code changes vs old unity editor" src="https://user-images.githubusercontent.com/65875290/225726389-9152f2b6-6ca8-449f-96e0-06de2ffa9803.png">

Figure 2.0 ^

Build on the left shows fixed build that does not have visual inconsistency regarding lighting and shadows. Build on the right was the original build without fix.

**Comment by alhasacademy96** [comment]
<img width="675" alt="yamlyfile-boards are working - latest build 2021 with code changes" src="https://user-images.githubusercontent.com/65875290/229538363-8a2845ee-5d70-45a4-b005-d03f90b3b310.png">

Figure 3.0 ^

Signboards are working again :)
